import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Banner from '../components/banner'
import Card from '../components/card'

import coffeeStoresData from '../data/coffee-stores.json'

export async function getStaticProps(context) {
  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: process.env.NEXT_PUBLIC_FOURSQUARE_API_KEY
    }
  };
  fetch(
    'https://api.foursquare.com/v3/places/nearby?ll=45.694583,9.679952&query=caffetteria',
    options
  )
    .then(response => response.json())
    .then(data => console.log(data));
  return {
    props: {
      coffeeStores: coffeeStoresData
    }, // will be passed to the page component as props
  }
}

export default function Home({ coffeeStores }) {
  const handleOnBannerBtnClick = () => {
    console.log('hi banner button');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            alt="Hero Image"
            src="/static/hero-image.png"
            width={700}
            height={400}
          />
        </div>
        { coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
            {
              coffeeStores.map(({id, name, imgUrl}) => (
                <Card
                  key={id}
                  name={name}
                  imgUrl={imgUrl}
                  href={`/coffee-store/${id}`}
                  className={styles.card}
                />
              ))
            }
            </div>
          </>
        )}
      </main>
    </div>
  )
}
