import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Banner from '../components/banner'
import Card from '../components/card'

export async function getStaticProps(context) {
  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: process.env.NEXT_PUBLIC_FOURSQUARE_API_KEY
    }
  };
  const response = await fetch(
    'https://api.foursquare.com/v3/places/search?query=caffe&ll=45.694583%2C9.679952&fields=fsq_id%2Cname%2Cphotos&limit=6',
    options
  )
  const data = await response.json();
  return {
    props: {
      coffeeStores: data?.results
    }, // will be passed to the page component as props
  }
}

export default function Home({ coffeeStores }) {
  const handleOnBannerBtnClick = () => {
    console.log('hi banner button');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            alt="Hero Image"
            src="/static/hero-image.png"
            width={700}
            height={400}
          />
        </div>
        { coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Bergamo stores</h2>
            <div className={styles.cardLayout}>
            {
              coffeeStores.map(({fsq_id: id, name, photos}) => {
                const imageUrl = photos?.length > 0 ? `${photos?.[0]?.prefix}260x160${photos?.[0]?.suffix}` : 'https://via.placeholder.com/260x160';
                console.log('imageUrl', imageUrl);
                return (
                <Card
                  key={id}
                  name={name}
                  imgUrl={imageUrl}
                  href={`/coffee-store/${id}`}
                  className={styles.card}
                />
              )})
            }
            </div>
          </>
        )}
      </main>
    </div>
  )
}
